apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: udagram-front
  name: udagram-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-front
        api: external
    spec:
      containers:
      - image: arthur28/udagram-front
        name: udagram-front
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always
